### PR TITLE
Small review

### PR DESCRIPTION
**Pull request by cderv**
Just some small things I corrected while reading the current book in the plane

---
This change is [Reviewable](https://reviewable.io/reviews/dr-harper/rmarkdown-cookbook/156)

### CODE REVIEW

**Comment by cderv** [comment]
I let you merge it. Unless you authorize me to merge directly.

**Comment by dr-harper** [comment]
Hey @cderv , been meaning to say thanks for this! House move almost settled down so will have time to go through this week.

**Comment by cderv** [comment]
ok. I did not advance much but waiting to work together on this book so that we really could have a reviewer workflow. Tell me when you are ready. I had other changes in mind regarding folder organisation.

**Comment by dr-harper** [comment]
Thanks for all these changes @cderv! Always useful to have someone else check for typos. Merging these now :)

**Pull request merged**
